=== 2010jmatpon/ExamenUD4-LMSGI/ExamenUD4/Ejercicio1/ejercicio1.dtd
<!ELEMENT ejercicio1 (sucursal*)>
<!ELEMENT sucursal (nombre, fecha_pedido, observaciones, articulo)>
    <!ATTLIST sucursal codigo CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fecha_pedido (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>
<!ELEMENT articulo (unidades, precio, plazo_revision)>
    <!ATTLIST articulo cod CDATA #REQUIRED>
<!ELEMENT unidades (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT plazo_revision (#PCDATA)>

=== 2010jmatpon/ExamenUD4-LMSGI/ExamenUD4/Ejercicio1/ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ejercicio1 SYSTEM "ejercicio1.dtd">
<ejercicio1>
    <sucursal codigo="H8690398">
        <nombre>Francisco Garcia</nombre>
        <fecha_pedido>17-05-2007</fecha_pedido>
        <observaciones>Urgente</observaciones>
        <articulo cod="JHD-849">
            <unidades>2</unidades>
            <precio>27'95â‚¬</precio>
            <plazo_revision>15-07-2007</plazo_revision>
        </articulo>
    </sucursal>
</ejercicio1>
