=== 2010jmatpon/ExamenUD4-LMSGI/ExamenUD4/Ejercicio1/ejercicio1Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ejercicio1" />
    <xs:complexType name="sucursales">
        <xs:sequence>
            <xs:element name="sucursal" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                        <xs:element name="fecha_pedido" type="xs:string"/>
                        <xs:element name="observaciones" type="xs:string"/>
                        <xs:element name="articulo" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="unidades" type="xs:string"/>
                                    <xs:element name="precio" type="xs:string"/>
                                    <xs:element name="plazo_revision" type="xs:string"/>
                                </xs:sequence>
                                <xs:attribute name="cod" type="xs:string"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="codigo" type="xs:string"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="codigo">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-Z]{1} 0-9){8}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="cod">
        <xs:restriction base="xs:string"></xs:restriction>
    </xs:simpleType>
</xs:schema>

=== 2010jmatpon/ExamenUD4-LMSGI/ExamenUD4/Ejercicio1/ejercicio1Schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<ejercicio1 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="ejercicio1Schema.xsd">
    <sucursal codigo="H8690398">
        <nombre>Francisco Garcia</nombre>
        <fecha_pedido>17-05-2007</fecha_pedido>
        <observaciones>Urgente</observaciones>
        <articulo cod="JHD-849">
            <unidades></unidades>
            <precio></precio>
            <plazo_revision></plazo_revision>
        </articulo>
    </sucursal>
</ejercicio1>
